Repository 123callumb/case-studies-basic-implementation, pull requests merged in 2021-03, with the labels that each got.

#48 Password Hashing
  Application/Application_Documentation.md
  Application/Application_Documentation.xml
  Application/Controllers/AuthenticationController.cs
  Application/Requests/Authentication/UserLogonRequest.cs
  Application/Views/Authentication/Login.cshtml
  Application/wwwroot/js/login.js
  Services/AuthenticationManagement/IAuthenticationManager.cs
  Services/AuthenticationManagement/Implementation/AuthenticationManager.cs
  Services/Database/PreDeploymentScript.sql
  Services/EntityFramework/DbEntities/DatabaseContext.cs
  Services/EntityFramework/DbEntities/User.cs
  Services/EntityFramework/DbEntities/VendorUser.cs
  Services/Filters/GlobalActionFilter.cs
  Services/HashManagement/Helpers/HashHelper.cs
  Services/Models/Abstract/AbstractUser.cs
  Services/Models/DTOs/ExternalUserDTO.cs
  Services/Models/DTOs/InternalUserDTO.cs
  Services/Services.md
  Services/Services.xml
  UnitTests/ControllerTests/AuthenticationControllerTests.cs
  UnitTests/ManagerTests/AuthenticationManagerTests.cs
  UnitTests/ManagerTests/HashHelperTests.cs
Labels: feature, individual enhancement

#49 Text to speech voice assistance feature
  Application/Views/Authentication/Login.cshtml
  Application/Views/Home/Index.cshtml
  Application/Views/Home/VendorCatalogue.cshtml
  Application/Views/Home/VendorMenu.cshtml
  Application/Views/Home/VendorQuotes.cshtml
  Application/Views/QuoteResponse/QuoteResponseModal.cshtml
  Application/Views/Shared/_Layout.cshtml
  Application/Views/VendorHome/Index.cshtml
  Application/wwwroot/js/site.js
  Application/wwwroot/js/vendor-home.js
  Application/wwwroot/lib/talkify/audioReader.js
  Application/wwwroot/lib/talkify/styles/classic-control-center/colors.css
  Application/wwwroot/lib/talkify/styles/classic-control-center/main.css
  Application/wwwroot/lib/talkify/styles/colors.css
  Application/wwwroot/lib/talkify/styles/local-control-center/colors.css
  Application/wwwroot/lib/talkify/styles/local-control-center/main.css
  Application/wwwroot/lib/talkify/styles/modern-control-center/colors.css
  Application/wwwroot/lib/talkify/styles/modern-control-center/main.css
  Application/wwwroot/lib/talkify/styles/talkify-common.css
  Application/wwwroot/lib/talkify/styles/talkify-playlist.css
  Application/wwwroot/lib/talkify/styles/text-selection-activator/colors.css
  Application/wwwroot/lib/talkify/styles/text-selection-activator/main.css
  Application/wwwroot/lib/talkify/talkify.min.js
  package-lock.json
Labels: feature, individual enhancement

#51 Logout functionality
  Application/Application.csproj
  Application/Controllers/AuthenticationController.cs
  Application/Views/Authentication/Login.cshtml
  Services/Services.csproj
Labels: feature

#53 Added Audio assistance to newly added modal
  Application/Views/InternalResponse/QuoteResponderModal.cshtml
  Application/Views/InternalResponse/VendorQuotes.cshtml
  Application/wwwroot/js/quote-responder-modal.js
  Application/wwwroot/js/vendor-home.js
  Application/wwwroot/lib/talkify/audioReader.js
Labels: feature, individual enhancement

#56 Added cookie for keeping audio assistance on
  Application/Views/Shared/_Layout.cshtml
  Application/wwwroot/lib/talkify/audioReader.js
Labels: individual enhancement, internal improvement

#59 Documentation for remaining controllers
  Application/Application.csproj
  Application/Application_Documentation.md
  Application/Application_Documentation.xml
  Application/Controllers/HomeController.cs
  Application/Controllers/InternalResponseController.cs
  Application/Controllers/VendorCatalogueController.cs
  Application/Controllers/VendorHomeController.cs
  Application/Views/VendorCatalogue/Index.cshtml
Labels: documentation
